### ISSUE TITLE
Organization作りません？

### ISSUE THREAD

**Issue by ryutah** [yoshioH/dokushokai#1]
ちょっと原の輪読会資料やるのに適当にforkしちゃったんですけど、今後も適当にいろいろとやる感じするんでOrganization作っちゃいません？

**Comment by yoshioH** [comment]
そこまでする必要あるかなって思ってたけど、あって困ることもないし、作っちゃっていいと思うよー。

**Comment by ryutah** [comment]
Organization作ったぜ！Close！

https://github.com/dokurin
